version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pineapple-lead-api
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-pineapple_leads}
      - DB_SSLMODE=disable
      - PORT=9000
      - REQUEST_TIMEOUT=30
      - MAX_CONCURRENT_CALLS=10
      - LEAD_TRANSFER_ENDPOINT=${LEAD_TRANSFER_ENDPOINT:-http://gw-test.pineapple.co.za/users/motor_lead}
      - QUICK_QUOTE_ENDPOINT=${QUICK_QUOTE_ENDPOINT:-http://gw-test.pineapple.co.za/api/v1/quote/quick-quote}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pineapple-network

  postgres:
    image: postgres:14-alpine
    container_name: pineapple-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-pineapple_leads}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pineapple-network

networks:
  pineapple-network:
    driver: bridge

volumes:
  postgres_data:
