version: "3.8"

services:
  api:
    build: .
    ports:
      - "4999:4999"
    volumes:
      - .:/app
    env_file:
      - app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - pineapple_network

networks:
  pineapple_network:
    driver: bridge
