version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
      - DEBUG=true
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Uncomment if you want to add Redis
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
