version: "3.8"

services:
  api:
    build: .
    image: pineapple-lead-api
    ports:
      - "${PORT:-9000}:${PORT:-9000}"
    volumes:
      - ./app:/app/app # Mount only the app directory for development
    env_file:
      - .env
    environment:
      - PORT=${PORT:-9000}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PINEAPPLE_API_URL=${PINEAPPLE_API_URL}
      - PINEAPPLE_API_BEARER_TOKEN=${PINEAPPLE_API_BEARER_TOKEN}
      - PINEAPPLE_SOURCE_NAME=${PINEAPPLE_SOURCE_NAME:-SureStrat}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-9000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - pineapple_network

networks:
  pineapple_network:
    driver: bridge
